### PR TITLE
Add .travis.yml with PyPi CI

### PR DESCRIPTION
**Pull request by pinin4fjords**
Here you go @anjaf - I believe this is what is required to create a new PyPi release for you every time you tag on master. We'll need also need to merge this to master from develop once you approve. 

Once that's done, let me know if it works next time you tag a release.

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Hmm. Not sure why this is failing!

**Comment by pinin4fjords** [comment]
All good now @anjaf - ready for review. Note that you could have a more comprehensive test suite in here than the --help I'm using above.

**Comment by anjaf** [comment]
Thanks Jon. Will take your word for it.

**Comment by pinin4fjords** [comment]
Okay, thanks @anjaf - fingers crossed.

**Pull request merged**
